#!/usr/bin/expect
set timeout 60
if {$argc == 1} {
    spawn [lindex $argv 0] -h test.easybox.host
} else {
    spawn [lindex $argv 0] [lindex $argv 1] -h test.easybox.host
}
exec sleep 1
expect "login:"
send "login_test\r"
expect "Password:"
send "123\r"
expect "login_test"
exec sleep 0.5
send "who | grep test.easybox.host > /dev/null && echo found\r"
expect "login_test"
exec sleep 0.5
send "exit\r"
expect eof
